service: wall
image: kalashnikovisme/wall
servers:
  web:
    - <%= ENV['MAIN_HOST'] %>
  anycable-rpc:
    traefik: true
    hosts:
      - <%= ENV['MAIN_HOST'] %>
    cmd: bundle exec anycable --debug
    port: 50051
    env:
      clear: 
        ANYCABLE_RPC_HOST: 0.0.0.0:50051
    labels:
      traefik.tcp.routers.rpc.rule: 'HostSNI(`*`)'
      traefik.tcp.routers.rpc.entrypoints: rpc
      traefik.tcp.services.rpc.loadbalancer.server.port: 50051
  sidekiq:
    hosts:
      - <%= ENV['MAIN_HOST'] %>
    cmd: bundle exec sidekiq -C config/sidekiq.yml

traefik:
  options:
    publish:
      - 50051:50051
  args:
    entrypoints.web.address: ":80"
    entrypoints.rpc.address: ":50051"

registry:
  username: kalashnikovisme
  password:
    - MRSK_REGISTRY_PASSWORD

builder:
  multiarch: false
  args:
    DO_SPACES_KEY: <%= ENV['DO_SPACES_KEY'] %>
    DO_SPACES_SECRET: <%= ENV['DO_SPACES_SECRET'] %>
    DO_SPACES_BUCKET: <%= ENV['DO_SPACES_BUCKET'] %>
    DO_SPACES_REGION: <%= ENV['DO_SPACES_REGION'] %>

env:
  clear:
    ANYCABLE_REDIS_URL: "redis://:<%= ENV['REDIS_PASSWORD'] %>@<%= ENV['REDIS_HOST'] %>:6379/0"
    REDIS_URL: "redis://:<%= ENV['REDIS_PASSWORD'] %>@<%= ENV['REDIS_HOST'] %>:6379/1"
    CABLE_URL: "ws://<%= ENV['ANYCABLE_GO_HOST'] %>/cable"
  secret:
    - DB_HOST
    - DO_SPACES_KEY
    - DO_SPACES_SECRET
    - DO_SPACES_BUCKET
    - DO_SPACES_REGION
    - POSTGRES_USER
    - POSTGRES_DB
    - POSTGRES_PASSWORD
    - RAILS_MASTER_KEY
    - NEW_RELIC_KEY

accessories:
  db:
    image: postgres:15.0
    host: <%= ENV['DB_HOST'] %>
    port: 5432
    env:
      secret:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - POSTGRES_DB
    directories:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0.10
    host: <%= ENV['REDIS_HOST'] %>
    port: 6379
    cmd: redis-server --requirepass <%= ENV['REDIS_PASSWORD'] %>
    volumes:
      - /var/lib/redis:/data

  ws:
    image: anycable/anycable-go:1.3
    host: <%= ENV['ANYCABLE_GO_HOST'] %>
    port: "80:8080"
    env:
      clear:
        ANYCABLE_HOST: "0.0.0.0"
        ANYCABLE_PORT: 8080
        ANYCABLE_REDIS_URL: "redis://:<%= ENV['REDIS_PASSWORD'] %>@<%= ENV['REDIS_HOST'] %>:6379/0"
        ANYCABLE_RPC_HOST: "<%= ENV['MAIN_HOST'] %>:50051"
        ANYCABLE_DEBUG: true

  new_relic:
    image: newrelic/infrastructure:latest
    host: <%= ENV['MAIN_HOST'] %>
    env:
      clear:
        NRIA_LICENSE_KEY: <%= ENV['NEW_RELIC_KEY'] %>
    options:
      cap-add: SYS_PTRACE
      privileged: true
      pid: host
      volume:
        - "/:/host:ro"
        - "/var/run/docker.sock:/var/run/docker.sock"
